/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status of a [`ckmeans_ffi`] call.
 */
typedef enum CkmeansStatus {
    /**
     * The call succeeded.
     */
    CkmeansStatus_Ok = 0,
    /**
     * `classes` is 0.
     */
    CkmeansStatus_TooFewClasses = 1,
    /**
     * `classes` is greater than the number of data values.
     */
    CkmeansStatus_TooManyClasses = 2,
    /**
     * The data contains NaN.
     */
    CkmeansStatus_NanInput = 3,
    /**
     * The data pointer is null and the length is not 0.
     */
    CkmeansStatus_NullData = 4,
    /**
     * An internal error occurred.
     */
    CkmeansStatus_InternalError = 5,
} CkmeansStatus;

/**
 * Wrapper for a void pointer to a sequence of [`InternalArray`]s, and the sequence length. Used for FFI.
 *
 * Each sequence entry represents a single [ckmeans] result class.
 */
typedef struct WrapperArray {
    const void *data;
    size_t len;
} WrapperArray;

/**
 * Wrapper for a void pointer to a sequence of floats representing data to be clustered using
 * [ckmeans], and the sequence length. Used for FFI.
 */
typedef struct ExternalArray {
    const void *data;
    size_t len;
} ExternalArray;

/**
 * An FFI wrapper for [ckmeans].
 *
 * On success, the function writes [`CkmeansStatus::Ok`] to `status` and returns the clusters. On
 * failure, it writes the error to `status` and returns a [`WrapperArray`] with a null `data`
 * pointer and a `len` of 0. `status` can be null. The function does not panic across the FFI
 * boundary.
 *
 * Data returned by this function **must** be freed by calling [`drop_ckmeans_result`].
 *
 * # Safety
 *
 * - If `data.data` is not null, it must point to `data.len` initialised, aligned `f64` values.
 * - If `status` is not null, it must point to memory that is valid for a write of a
 *   [`CkmeansStatus`].
 */
struct WrapperArray ckmeans_ffi(struct ExternalArray data,
                                unsigned char classes,
                                enum CkmeansStatus *status);

/**
 * Drop data returned by [`ckmeans_ffi`]. A result with a null `data` pointer is ignored.
 *
 * # Safety
 *
 * `result` must be a value returned by [`ckmeans_ffi`], and it must not be dropped more than
 * once.
 */
void drop_ckmeans_result(struct WrapperArray result);
